name: inception

services:
  mariadb:
    env_file: ./.env
    build:
      context: ./requirements/mariadb
    image: mariadb
    restart: on-failure
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MARIADB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_root_password
      - db_password
    volumes:
      - wordpress-db:/var/lib/mysql
    networks:
      - inception-network

  wordpress:
    depends_on:
      - mariadb
    env_file: ./.env
    build:
      context: ./requirements/wordpress
    image: wordpress
    restart: on-failure
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MARIADB_PASSWORD_FILE: /run/secrets/db_password
      WORDPRESS_VERSION: ${WORDPRESS_VERSION}
      WORDPRESS_SHA1: ${WORDPRESS_SHA1}
      DOMAIN_NAME: ${DOMAIN_NAME}
      WORDPRESS_TITLE: ${WORDPRESS_TITLE}
      WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USER}
      WORDPRESS_ADMIN_PASSWORD_FILE: /run/secrets/wp_admin_password
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
      WORDPRESS_USER: ${WORDPRESS_USER}
      WORDPRESS_USER_PASSWORD_FILE: /run/secrets/wp_user_password
      WORDPRESS_USER_EMAIL: ${WORDPRESS_USER_EMAIL}
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password
    volumes:
      - wordpress-files:/var/www/html/
    networks:
      - inception-network

  nginx:
    depends_on:
      - wordpress
    env_file: ./.env
    build:
      context: ./requirements/nginx
    image: nginx
    ports:
      - "127.0.0.1:443:443"
    restart: on-failure
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      SSL_CERTIFICATE_FILE: /run/secrets/ssl_certificate
      SSL_PRIVATE_KEY_FILE: /run/secrets/ssl_private_key
    secrets:
      - ssl_certificate
      - ssl_private_key
    volumes:
      - wordpress-files:/var/www/html/
    networks:
      - inception-network

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  ssl_certificate:
    file: ../secrets/cert.pem
  ssl_private_key:
    file: ../secrets/key.pem
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt

networks:
  inception-network:
    driver: bridge

volumes:
  wordpress-db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/anaqvi/data/wordpress-db'
  wordpress-files:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/anaqvi/data/wordpress-files'
